[package]
name = "hgb-cli"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[lib]
name = "hgb_cli"
path = "src/lib.rs"

[[bin]]
name = "hgb"
path = "src/main.rs"

[dependencies]
hgb-core = { path = "../hgb-core" }
hgb-daemon = { path = "../hgb-daemon" }
hgb-nextgen = { path = "../hgb-nextgen" }
hgb-storage = { path = "../hgb-storage" }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
bincode = { workspace = true }
clap = { workspace = true }
colored = { workspace = true }
thiserror = { workspace = true }
crossterm = { workspace = true }
unicode-width = { workspace = true }
ratatui = { workspace = true }
chrono = { workspace = true }
uuid = { version = "1.27.0", features = ["v4"] }

[dev-dependencies]
hgb-storage = { path = "../hgb-storage" }
async-trait = { workspace = true }
reqwest = { workspace = true }
rusqlite = { workspace = true }
chrono = { workspace = true }
hmac = "0.12.0"
sha2.workspace = true
hex = "0.4.3"
