use std::fs;
use std::path::{Path, PathBuf};
use serde::{Deserialize, Serialize};
use hgb_core::error::Result;

/// Severity classification of a Red Team finding.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
pub enum RedTeamSeverity {
    Informational,
    Low,
    Medium,
    High,
    Critical,
}

impl RedTeamSeverity {
    pub fn badge(&self) -> &'static str {
        match self {
            Self::Critical => "🚨 CRITICAL",
            Self::High => "🔴 HIGH",
            Self::Medium => "🟡 MEDIUM",
            Self::Low => "🔵 LOW",
            Self::Informational => "ℹ️ INFO",
        }
    }
}

/// Vulnerability category inspected by the Red Team auditor.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum RedTeamCategory {
    TenantIsolationLeak,
    UnboundedQuery,
    AlgorithmicComplexity,
    ConcurrencyHazard,
    SecretLeak,
    IdorVulnerability,
    MissingRateLimit,
}

impl RedTeamCategory {
    pub fn name(&self) -> &'static str {
        match self {
            Self::TenantIsolationLeak => "Multi-Tenant / Auth Isolation Leak",
            Self::UnboundedQuery => "Unbounded Query / Memory Exhaustion",
            Self::AlgorithmicComplexity => "O(N^2) Algorithmic Complexity Bottleneck",
            Self::ConcurrencyHazard => "Concurrency Hazard / Race Condition",
            Self::SecretLeak => "Hardcoded Secret / Credential Leak",
            Self::IdorVulnerability => "IDOR (Insecure Direct Object Reference)",
            Self::MissingRateLimit => "Missing Rate Limiter on Expensive Endpoint",
        }
    }
}

/// An individual finding surfaced by the Red Team auditor.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RedTeamFinding {
    pub id: String,
    pub category: RedTeamCategory,
    pub severity: RedTeamSeverity,
    pub file: Option<PathBuf>,
    pub line: Option<usize>,
    pub snippet: Option<String>,
    pub title: String,
    pub description: String,
    pub exploit_scenario: String,
    pub recommended_fix: String,
    pub suggested_patch: Option<String>,
}

/// Verdict on whether the code is safe to deploy or merge.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum RedTeamVerdict {
    Clean,
    Caution,
    Blocked,
}

impl RedTeamVerdict {
    pub fn badge(&self) -> &'static str {
        match self {
            Self::Clean => "✅ PASS (CLEAN)",
            Self::Caution => "⚠️ CAUTION (WARNINGS)",
            Self::Blocked => "⛔ BLOCKED (CRITICAL VULNERABILITIES)",
        }
    }
}

/// Comprehensive report generated by the Red Team Auditor.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RedTeamReport {
    pub findings: Vec<RedTeamFinding>,
    pub files_scanned: usize,
    pub total_critical: usize,
    pub total_high: usize,
    pub total_medium: usize,
    pub total_low: usize,
    pub verdict: RedTeamVerdict,
    pub summary: String,
}

impl RedTeamReport {
    pub fn new(findings: Vec<RedTeamFinding>, files_scanned: usize) -> Self {
        let mut total_critical = 0;
        let mut total_high = 0;
        let mut total_medium = 0;
        let mut total_low = 0;

        for f in &findings {
            match f.severity {
                RedTeamSeverity::Critical => total_critical += 1,
                RedTeamSeverity::High => total_high += 1,
                RedTeamSeverity::Medium => total_medium += 1,
                RedTeamSeverity::Low | RedTeamSeverity::Informational => total_low += 1,
            }
        }

        let verdict = if total_critical > 0 {
            RedTeamVerdict::Blocked
        } else if total_high > 0 || total_medium > 0 {
            RedTeamVerdict::Caution
        } else {
            RedTeamVerdict::Clean
        };

        let summary = format!(
            "Scanned {} target(s): {} findings ({} Critical, {} High, {} Medium, {} Low). Verdict: {}",
            files_scanned,
            findings.len(),
            total_critical,
            total_high,
            total_medium,
            total_low,
            verdict.badge()
        );

        Self {
            findings,
            files_scanned,
            total_critical,
            total_high,
            total_medium,
            total_low,
            verdict,
            summary,
        }
    }

    pub fn to_markdown(&self) -> String {
        let mut out = String::new();
        out.push_str("# 🛡️ Hagibis Adversarial Red-Team & Edge-Case Audit Report\n\n");
        out.push_str(&format!("**Verdict**: {}\n\n", self.verdict.badge()));
        out.push_str(&format!("{}\n\n", self.summary));

        if self.findings.is_empty() {
            out.push_str("✨ **No security or architectural hazards detected. Code is robust!**\n");
            return out;
        }

        out.push_str("## 🎯 Discovered Findings\n\n");
        for (idx, finding) in self.findings.iter().enumerate() {
            out.push_str(&format!("### {}. {} - {}\n", idx + 1, finding.severity.badge(), finding.title));
            out.push_str(&format!("- **Category**: {}\n", finding.category.name()));
            if let Some(ref file) = finding.file {
                let line_str = finding.line.map(|l| format!(":{}", l)).unwrap_or_default();
                out.push_str(&format!("- **Location**: `{}`{}\n", file.display(), line_str));
            }
            if let Some(ref snip) = finding.snippet {
                out.push_str(&format!("- **Offending Code**:\n```text\n{}\n```\n", snip));
            }
            out.push_str(&format!("- **Exploit / Hazard Scenario**: {}\n", finding.exploit_scenario));
            out.push_str(&format!("- **Remediation**: {}\n", finding.recommended_fix));
            if let Some(ref patch) = finding.suggested_patch {
                out.push_str(&format!("- **Suggested Patch**:\n```diff\n{}\n```\n", patch));
            }
            out.push_str("\n");
        }
        out
    }

    pub fn render_terminal_card(&self) -> String {
        let mut card = String::new();
        card.push_str(&format!("┌─ RED-TEAM AUDIT [{}] ───────────────────\n", self.verdict.badge()));
        card.push_str(&format!("│ Scanned: {} files | Findings: {}\n", self.files_scanned, self.findings.len()));
        if !self.findings.is_empty() {
            card.push_str("├────────────────────────────────────────────────────────────\n");
            for finding in self.findings.iter().take(5) {
                let loc = finding.file.as_ref()
                    .map(|f| f.file_name().unwrap_or_default().to_string_lossy().to_string())
                    .unwrap_or_else(|| "snippet".to_string());
                let line = finding.line.map(|l| format!(":{}", l)).unwrap_or_default();
                card.push_str(&format!("│ {} [{}{}] {}\n", finding.severity.badge(), loc, line, finding.title));
                card.push_str(&format!("│   └─ Fix: {}\n", finding.recommended_fix));
            }
            if self.findings.len() > 5 {
                card.push_str(&format!("│   ... and {} more findings\n", self.findings.len() - 5));
            }
        }
        card.push_str("└────────────────────────────────────────────────────────────\n");
        card
    }
}

/// The Adversarial Red-Team Auditor Engine.
#[derive(Debug, Default, Clone)]
pub struct RedTeamAuditor;

impl RedTeamAuditor {
    pub fn new() -> Self {
        Self
    }

    /// Audits a raw code snippet.
    pub fn audit_code(&self, code: &str, file_hint: Option<&Path>) -> RedTeamReport {
        let mut findings = Vec::new();
        let lines: Vec<&str> = code.lines().collect();

        for (idx, line) in lines.iter().enumerate() {
            let line_num = idx + 1;
            let trimmed = line.trim();

            // 1. Unbounded SQL Queries (SELECT * without LIMIT or WHERE)
            let upper = trimmed.to_uppercase();
            if upper.contains("SELECT ") && upper.contains(" FROM ") && !upper.contains(" LIMIT ") {
                if upper.contains("SELECT *") || !upper.contains(" WHERE ") {
                    findings.push(RedTeamFinding {
                        id: format!("RT-UNBOUNDED-{}", line_num),
                        category: RedTeamCategory::UnboundedQuery,
                        severity: RedTeamSeverity::High,
                        file: file_hint.map(|p| p.to_path_buf()),
                        line: Some(line_num),
                        snippet: Some(trimmed.to_string()),
                        title: "Unbounded Database Query Detected".to_string(),
                        description: "Executing SQL queries without a LIMIT clause can saturate DB connection pools and crash the app with OOM on large datasets.".to_string(),
                        exploit_scenario: "Attacker seeds 100,000 records; calling this endpoint exhausts memory and causes denial of service.".to_string(),
                        recommended_fix: "Add an explicit 'LIMIT <n>' or implement keyset/cursor pagination.".to_string(),
                        suggested_patch: Some(format!("- {}\n+ {} LIMIT 100", trimmed, trimmed)),
                    });
                }
            }

            // 2. Tenant Isolation Leak in multi-tenant contexts
            if (upper.contains("SELECT ") || upper.contains("UPDATE ") || upper.contains("DELETE "))
                && upper.contains(" WHERE ")
                && !upper.contains("TENANT_ID")
                && !upper.contains("ORGANIZATION_ID")
                && !upper.contains("ORG_ID")
                && (upper.contains("FROM ACCOUNTS") || upper.contains("FROM USERS") || upper.contains("FROM ORDERS") || upper.contains("FROM INVOICES"))
            {
                findings.push(RedTeamFinding {
                    id: format!("RT-TENANT-LEAK-{}", line_num),
                    category: RedTeamCategory::TenantIsolationLeak,
                    severity: RedTeamSeverity::Critical,
                    file: file_hint.map(|p| p.to_path_buf()),
                    line: Some(line_num),
                    snippet: Some(trimmed.to_string()),
                    title: "Missing Tenant Isolation Filter".to_string(),
                    description: "Database operation touches multi-tenant table without verifying tenant_id or org_id.".to_string(),
                    exploit_scenario: "Tenant A modifies or views financial/user data belonging to Tenant B by manipulating record IDs.".to_string(),
                    recommended_fix: "Always bind tenant_id in the WHERE predicate: 'AND tenant_id = :tenant_id'.".to_string(),
                    suggested_patch: Some(format!("- {}\n+ {} AND tenant_id = :tenant_id", trimmed, trimmed)),
                });
            }

            // 3. Concurrency Hazard: static mut in Rust
            if trimmed.contains("static mut ") {
                findings.push(RedTeamFinding {
                    id: format!("RT-CONCURRENCY-STATIC-MUT-{}", line_num),
                    category: RedTeamCategory::ConcurrencyHazard,
                    severity: RedTeamSeverity::Critical,
                    file: file_hint.map(|p| p.to_path_buf()),
                    line: Some(line_num),
                    snippet: Some(trimmed.to_string()),
                    title: "Dangerous 'static mut' Variable in Rust".to_string(),
                    description: "Rust 2024 and concurrency best practices forbid static mut due to ubiquitous data races.".to_string(),
                    exploit_scenario: "Multiple incoming async requests access static mut simultaneously, corrupting pointers and crashing process.".to_string(),
                    recommended_fix: "Use std::sync::atomic types, Mutex<T>, RwLock<T>, or OnceLock<T>.".to_string(),
                    suggested_patch: Some(format!("- {}\n+ static VAR: std::sync::atomic::AtomicUsize = ...;", trimmed)),
                });
            }

            // 4. Hardcoded Secrets / Keys
            if (trimmed.contains("AKIA") && trimmed.len() > 16)
                || (trimmed.contains("ghp_") && trimmed.len() > 20)
                || (trimmed.contains("sk-") && (trimmed.contains("openai") || trimmed.contains("anthropic") || trimmed.len() > 30))
                || ((trimmed.contains("password = \"") || trimmed.contains("api_key = \"") || trimmed.contains("secret = \"")) && !trimmed.contains("env::var"))
            {
                findings.push(RedTeamFinding {
                    id: format!("RT-SECRET-{}", line_num),
                    category: RedTeamCategory::SecretLeak,
                    severity: RedTeamSeverity::Critical,
                    file: file_hint.map(|p| p.to_path_buf()),
                    line: Some(line_num),
                    snippet: Some(trimmed.to_string()),
                    title: "Hardcoded Secret / API Token Detected".to_string(),
                    description: "High-entropy API token or secret string committed directly in code.".to_string(),
                    exploit_scenario: "Public repo clone allows malicious actors to drain cloud accounts or compromise credentials.".to_string(),
                    recommended_fix: "Load secrets from environment variables (e.g. std::env::var) or a secret manager.".to_string(),
                    suggested_patch: Some("- <hardcoded secret>\n+ std::env::var(\"API_KEY\").unwrap()".to_string()),
                });
            }

            // 5. Insecure Direct Object Reference (IDOR) pattern
            if (trimmed.contains("get_by_id(id)") || trimmed.contains("delete(id)") || trimmed.contains("update(id,"))
                && !trimmed.contains("user_id")
                && !trimmed.contains("auth")
                && !trimmed.contains("tenant")
            {
                findings.push(RedTeamFinding {
                    id: format!("RT-IDOR-{}", line_num),
                    category: RedTeamCategory::IdorVulnerability,
                    severity: RedTeamSeverity::High,
                    file: file_hint.map(|p| p.to_path_buf()),
                    line: Some(line_num),
                    snippet: Some(trimmed.to_string()),
                    title: "Potential IDOR Vulnerability in Entity Access".to_string(),
                    description: "Object fetched or modified solely by entity ID without checking caller ownership.".to_string(),
                    exploit_scenario: "Unprivileged user increments 'id=101' to 'id=102' in query param and modifies another user's profile.".to_string(),
                    recommended_fix: "Enforce caller ownership: 'WHERE id = :id AND user_id = :auth_user_id'.".to_string(),
                    suggested_patch: None,
                });
            }
        }

        // 6. Algorithmic Complexity: Scan for nested for loops without map lookup
        for (i, line) in lines.iter().enumerate() {
            let trimmed = line.trim();
            if trimmed.starts_with("for ") && trimmed.ends_with('{') {
                for (_j, inner_line) in lines.iter().enumerate().skip(i + 1).take(15) {
                    let inner_trimmed = inner_line.trim();
                    if inner_trimmed.starts_with("for ") && inner_trimmed.ends_with('{') {
                        findings.push(RedTeamFinding {
                            id: format!("RT-COMPLEXITY-O-N2-{}", i + 1),
                            category: RedTeamCategory::AlgorithmicComplexity,
                            severity: RedTeamSeverity::Medium,
                            file: file_hint.map(|p| p.to_path_buf()),
                            line: Some(i + 1),
                            snippet: Some(format!("{}\n    {}", trimmed, inner_trimmed)),
                            title: "Nested Iteration O(N^2) Complexity Warning".to_string(),
                            description: "Nested loops without index/hash map lookups cause quadratic slowdowns on larger collections.".to_string(),
                            exploit_scenario: "An input collection with 10,000 items results in 100,000,000 iterations, locking the event loop.".to_string(),
                            recommended_fix: "Pre-index the inner collection into a HashSet or HashMap for O(1) lookups.".to_string(),
                            suggested_patch: None,
                        });
                        break;
                    }
                }
            }
        }

        RedTeamReport::new(findings, 1)
    }

    /// Audits a git diff string.
    pub fn audit_diff(&self, diff: &str) -> RedTeamReport {
        let mut added_lines = String::new();
        for line in diff.lines() {
            if line.starts_with('+') && !line.starts_with("+++") {
                added_lines.push_str(&line[1..]);
                added_lines.push('\n');
            }
        }
        self.audit_code(&added_lines, None)
    }

    /// Audits a specific file on disk.
    pub fn audit_file(&self, path: &Path) -> Result<RedTeamReport> {
        let content = fs::read_to_string(path)?;
        Ok(self.audit_code(&content, Some(path)))
    }

    /// Audits all source files in a workspace.
    pub fn audit_workspace(&self, root: &Path) -> Result<RedTeamReport> {
        let mut all_findings = Vec::new();
        let mut files_scanned = 0;

        let mut files = Vec::new();
        collect_target_files(root, &mut files, 0, 5);

        for file in &files {
            if let Ok(content) = fs::read_to_string(file) {
                files_scanned += 1;
                let report = self.audit_code(&content, Some(file));
                all_findings.extend(report.findings);
            }
        }

        Ok(RedTeamReport::new(all_findings, files_scanned))
    }
}

fn collect_target_files(dir: &Path, files: &mut Vec<PathBuf>, depth: usize, max_depth: usize) {
    if depth > max_depth {
        return;
    }
    if let Ok(entries) = fs::read_dir(dir) {
        for entry in entries.flatten() {
            let path = entry.path();
            let file_name = path.file_name().unwrap_or_default().to_string_lossy();
            if file_name.starts_with('.') || file_name == "target" || file_name == "node_modules" {
                continue;
            }
            if path.is_dir() {
                collect_target_files(&path, files, depth + 1, max_depth);
            } else if let Some(ext) = path.extension().and_then(|s| s.to_str()) {
                if matches!(ext, "rs" | "ts" | "tsx" | "js" | "jsx" | "py" | "sql") {
                    files.push(path);
                }
            }
        }
    }
}
