use std::fs;
use std::path::{Path, PathBuf};
use serde::{Deserialize, Serialize};
use hgb_core::error::Result;
use hgb_core::providers::OllamaProvider;
use hgb_core::traits::HgbProvider;

/// Severity classification of a Red Team finding.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
pub enum RedTeamSeverity {
    Informational,
    Low,
    Medium,
    High,
    Critical,
}

impl RedTeamSeverity {
    pub fn badge(&self) -> &'static str {
        match self {
            Self::Critical => "🚨 CRITICAL",
            Self::High => "🔴 HIGH",
            Self::Medium => "🟡 MEDIUM",
            Self::Low => "🔵 LOW",
            Self::Informational => "ℹ️ INFO",
        }
    }
}

/// Vulnerability category inspected by the Red Team auditor.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum RedTeamCategory {
    TenantIsolationLeak,
    UnboundedQuery,
    AlgorithmicComplexity,
    ConcurrencyHazard,
    SecretLeak,
    IdorVulnerability,
    MissingRateLimit,
}

impl RedTeamCategory {
    pub fn name(&self) -> &'static str {
        match self {
            Self::TenantIsolationLeak => "Multi-Tenant / Auth Isolation Leak",
            Self::UnboundedQuery => "Unbounded Query / Memory Exhaustion",
            Self::AlgorithmicComplexity => "O(N^2) Algorithmic Complexity Bottleneck",
            Self::ConcurrencyHazard => "Concurrency Hazard / Race Condition",
            Self::SecretLeak => "Hardcoded Secret / Credential Leak",
            Self::IdorVulnerability => "IDOR (Insecure Direct Object Reference)",
            Self::MissingRateLimit => "Missing Rate Limiter on Expensive Endpoint",
        }
    }
}

/// An individual finding surfaced by the Red Team auditor.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RedTeamFinding {
    pub id: String,
    pub category: RedTeamCategory,
    pub severity: RedTeamSeverity,
    pub file: Option<PathBuf>,
    pub line: Option<usize>,
    pub snippet: Option<String>,
    pub title: String,
    pub description: String,
    pub exploit_scenario: String,
    pub recommended_fix: String,
    pub suggested_patch: Option<String>,
}

/// Verdict on whether the code is safe to deploy or merge.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum RedTeamVerdict {
    Clean,
    Caution,
    Blocked,
}

impl RedTeamVerdict {
    pub fn badge(&self) -> &'static str {
        match self {
            Self::Clean => "✅ PASS (CLEAN)",
            Self::Caution => "⚠️ CAUTION (WARNINGS)",
            Self::Blocked => "⛔ BLOCKED (CRITICAL VULNERABILITIES)",
        }
    }
}

/// Comprehensive report generated by the Red Team Auditor.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RedTeamReport {
    pub findings: Vec<RedTeamFinding>,
    pub files_scanned: usize,
    pub total_critical: usize,
    pub total_high: usize,
    pub total_medium: usize,
    pub total_low: usize,
    pub verdict: RedTeamVerdict,
    pub summary: String,
}

impl RedTeamReport {
    pub fn new(findings: Vec<RedTeamFinding>, files_scanned: usize) -> Self {
        let mut total_critical = 0;
        let mut total_high = 0;
        let mut total_medium = 0;
        let mut total_low = 0;

        for f in &findings {
            match f.severity {
                RedTeamSeverity::Critical => total_critical += 1,
                RedTeamSeverity::High => total_high += 1,
                RedTeamSeverity::Medium => total_medium += 1,
                RedTeamSeverity::Low | RedTeamSeverity::Informational => total_low += 1,
            }
        }

        let verdict = if total_critical > 0 {
            RedTeamVerdict::Blocked
        } else if total_high > 0 || total_medium > 0 {
            RedTeamVerdict::Caution
        } else {
            RedTeamVerdict::Clean
        };

        let summary = format!(
            "Scanned {} target(s): {} findings ({} Critical, {} High, {} Medium, {} Low). Verdict: {}",
            files_scanned,
            findings.len(),
            total_critical,
            total_high,
            total_medium,
            total_low,
            verdict.badge()
        );

        Self {
            findings,
            files_scanned,
            total_critical,
            total_high,
            total_medium,
            total_low,
            verdict,
            summary,
        }
    }

    pub fn to_markdown(&self) -> String {
        let mut out = String::new();
        out.push_str("# 🛡️ Hagibis Adversarial Red-Team & Edge-Case Audit Report\n\n");
        out.push_str(&format!("**Verdict**: {}\n\n", self.verdict.badge()));
        out.push_str(&format!("{}\n\n", self.summary));

        if self.findings.is_empty() {
            out.push_str("✨ **No security or architectural hazards detected. Code is robust!**\n");
            return out;
        }

        out.push_str("## 🎯 Discovered Findings\n\n");
        for (idx, finding) in self.findings.iter().enumerate() {
            out.push_str(&format!("### {}. {} - {}\n", idx + 1, finding.severity.badge(), finding.title));
            out.push_str(&format!("- **Category**: {}\n", finding.category.name()));
            if let Some(ref file) = finding.file {
                let line_str = finding.line.map(|l| format!(":{}", l)).unwrap_or_default();
                out.push_str(&format!("- **Location**: `{}`{}\n", file.display(), line_str));
            }
            if let Some(ref snip) = finding.snippet {
                out.push_str(&format!("- **Offending Code**:\n```text\n{}\n```\n", snip));
            }
            out.push_str(&format!("- **Exploit / Hazard Scenario**: {}\n", finding.exploit_scenario));
            out.push_str(&format!("- **Remediation**: {}\n", finding.recommended_fix));
            if let Some(ref patch) = finding.suggested_patch {
                out.push_str(&format!("- **Suggested Patch**:\n```diff\n{}\n```\n", patch));
            }
            out.push_str("\n");
        }
        out
    }

    pub fn render_terminal_card(&self) -> String {
        let mut card = String::new();
        card.push_str(&format!("┌─ RED-TEAM AUDIT [{}] ───────────────────\n", self.verdict.badge()));
        card.push_str(&format!("│ Scanned: {} files | Findings: {}\n", self.files_scanned, self.findings.len()));
        if !self.findings.is_empty() {
            card.push_str("├────────────────────────────────────────────────────────────\n");
            for finding in self.findings.iter().take(5) {
                let loc = finding.file.as_ref()
                    .map(|f| f.file_name().unwrap_or_default().to_string_lossy().to_string())
                    .unwrap_or_else(|| "snippet".to_string());
                let line = finding.line.map(|l| format!(":{}", l)).unwrap_or_default();
                card.push_str(&format!("│ {} [{}{}] {}\n", finding.severity.badge(), loc, line, finding.title));
                card.push_str(&format!("│   └─ Fix: {}\n", finding.recommended_fix));
            }
            if self.findings.len() > 5 {
                card.push_str(&format!("│   ... and {} more findings\n", self.findings.len() - 5));
            }
        }
        card.push_str("└────────────────────────────────────────────────────────────\n");
        card
    }
}

/// The Adversarial Red-Team Auditor Engine.
#[derive(Debug, Default, Clone)]
pub struct RedTeamAuditor;

impl RedTeamAuditor {
    pub fn new() -> Self {
        Self
    }

    /// Audits a raw code snippet.
    pub async fn audit_code(&self, code: &str, file_hint: Option<&Path>) -> RedTeamReport {
        let provider = OllamaProvider::new(None, Some("qwen2.5-coder:7b".to_string()));
        let prompt = format!(
            "Analyze the following code for security vulnerabilities, concurrency hazards, secret leaks, etc.
Respond ONLY with a JSON object matching this schema:
{{
  \"findings\": [
    {{
      \"id\": \"RT-...\",
      \"category\": \"SecretLeak\" | \"IdorVulnerability\" | \"ConcurrencyHazard\" | \"UnboundedQuery\" | \"AlgorithmicComplexity\",
      \"severity\": \"Informational\" | \"Low\" | \"Medium\" | \"High\" | \"Critical\",
      \"line\": 10,
      \"snippet\": \"code snippet\",
      \"title\": \"short title\",
      \"description\": \"details\",
      \"exploit_scenario\": \"how to exploit\",
      \"recommended_fix\": \"how to fix\",
      \"suggested_patch\": \"diff patch\"
    }}
  ]
}}
Code to analyze:
{}",
            code
        );

        let resp = match provider.complete(&prompt, None).await {
            Ok(r) => r,
            Err(_) => return RedTeamReport::new(vec![], 1),
        };

        let start = resp.find('{').unwrap_or(0);
        let end = resp.rfind('}').unwrap_or(resp.len() - 1) + 1;
        let json_str = &resp[start..end];

        #[derive(serde::Deserialize)]
        struct Resp {
            findings: Vec<RedTeamFinding>,
        }

        let mut findings = match serde_json::from_str::<Resp>(json_str) {
            Ok(parsed) => parsed.findings,
            Err(_) => vec![],
        };

        for f in &mut findings {
            f.file = file_hint.map(|p| p.to_path_buf());
        }

        RedTeamReport::new(findings, 1)
    }

    /// Audits a git diff string.
    pub async fn audit_diff(&self, diff: &str) -> RedTeamReport {
        let mut added_lines = String::new();
        for line in diff.lines() {
            if line.starts_with('+') && !line.starts_with("+++") {
                added_lines.push_str(&line[1..]);
                added_lines.push('\n');
            }
        }
        self.audit_code(&added_lines, None).await
    }

    /// Audits a specific file on disk.
    pub async fn audit_file(&self, path: &Path) -> Result<RedTeamReport> {
        let content = fs::read_to_string(path)?;
        Ok(self.audit_code(&content, Some(path)).await)
    }

    /// Audits all source files in a workspace.
    pub async fn audit_workspace(&self, root: &Path) -> Result<RedTeamReport> {
        let mut all_findings = Vec::new();
        let mut files_scanned = 0;

        let mut files = Vec::new();
        collect_target_files(root, &mut files, 0, 5);

        for file in &files {
            if let Ok(content) = fs::read_to_string(file) {
                files_scanned += 1;
                let report = self.audit_code(&content, Some(file)).await;
                all_findings.extend(report.findings);
            }
        }

        Ok(RedTeamReport::new(all_findings, files_scanned))
    }
}

fn collect_target_files(dir: &Path, files: &mut Vec<PathBuf>, depth: usize, max_depth: usize) {
    if depth > max_depth {
        return;
    }
    if let Ok(entries) = fs::read_dir(dir) {
        for entry in entries.flatten() {
            let path = entry.path();
            let file_name = path.file_name().unwrap_or_default().to_string_lossy();
            if file_name.starts_with('.') || file_name == "target" || file_name == "node_modules" {
                continue;
            }
            if path.is_dir() {
                collect_target_files(&path, files, depth + 1, max_depth);
            } else if let Some(ext) = path.extension().and_then(|s| s.to_str()) {
                if matches!(ext, "rs" | "ts" | "tsx" | "js" | "jsx" | "py" | "sql") {
                    files.push(path);
                }
            }
        }
    }
}
